import {
  Laptop,
  Coins,
  Flame,
  Music,
  Trophy,
  Palette,
  Shirt,
  Camera,
  Landmark,
  Gamepad2,
  Brush,
  Video,
  Sparkles,
  PenTool,
  Feather,
  Paintbrush,
} from 'lucide-react';

export const MAIN_INTERESTS = [
  {
    id: 'Tech',
    name: 'Tech',
    emoji: '💻',
    icon: Laptop,
    tagline: 'Hackathons, coding & AI workshops',
    color: 'from-blue-500/10 to-indigo-500/10 border-blue-500/30 text-blue-600',
    activeBadge: 'bg-blue-600 text-white',
  },
  {
    id: 'Finance',
    name: 'Finance',
    emoji: '💰',
    icon: Coins,
    tagline: 'Competitions, investing & case studies',
    color: 'from-emerald-500/10 to-teal-500/10 border-emerald-500/30 text-emerald-600',
    activeBadge: 'bg-emerald-600 text-white',
  },
  {
    id: 'Dance',
    name: 'Dance',
    emoji: '💃',
    icon: Flame,
    tagline: 'Auditions, workshops & choreography',
    color: 'from-rose-500/10 to-pink-500/10 border-rose-500/30 text-rose-600',
    activeBadge: 'bg-rose-600 text-white',
  },
  {
    id: 'Music',
    name: 'Music',
    emoji: '🎵',
    icon: Music,
    tagline: 'Concerts, jams & acoustics',
    color: 'from-purple-500/10 to-violet-500/10 border-purple-500/30 text-purple-600',
    activeBadge: 'bg-purple-600 text-white',
  },
  {
    id: 'Sports',
    name: 'Sports',
    emoji: '⚽',
    icon: Trophy,
    tagline: 'Tournaments, leagues & athletics',
    color: 'from-amber-500/10 to-orange-500/10 border-amber-500/30 text-amber-600',
    activeBadge: 'bg-amber-600 text-white',
  },
  {
    id: 'Creativity',
    name: 'Creativity',
    emoji: '🎨',
    icon: Palette,
    tagline: 'Art, design, writing & content creation',
    hasSubcategories: true,
    color: 'from-fuchsia-500/10 to-pink-500/10 border-fuchsia-500/30 text-fuchsia-600',
    activeBadge: 'bg-fuchsia-600 text-white',
  },
  {
    id: 'Fashion',
    name: 'Fashion',
    emoji: '👗',
    icon: Shirt,
    tagline: 'Styling, runway & apparel trends',
    color: 'from-pink-500/10 to-rose-500/10 border-pink-500/30 text-pink-600',
    activeBadge: 'bg-pink-600 text-white',
  },
  {
    id: 'Photography',
    name: 'Photography',
    emoji: '📸',
    icon: Camera,
    tagline: 'Photowalks, frames & cinematography',
    color: 'from-cyan-500/10 to-blue-500/10 border-cyan-500/30 text-cyan-600',
    activeBadge: 'bg-cyan-600 text-white',
  },
  {
    id: 'Architecture',
    name: 'Architecture',
    emoji: '🏛️',
    icon: Landmark,
    tagline: 'Spatial design, drafting & structures',
    color: 'from-stone-500/10 to-zinc-500/10 border-stone-500/30 text-stone-600',
    activeBadge: 'bg-stone-700 text-white',
  },
  {
    id: 'Gaming',
    name: 'Gaming',
    emoji: '🎮',
    icon: Gamepad2,
    tagline: 'Esports, tournaments & gaming hubs',
    color: 'from-violet-500/10 to-indigo-500/10 border-violet-500/30 text-violet-600',
    activeBadge: 'bg-violet-600 text-white',
  },
];

export const CREATIVITY_SUBCATEGORIES = [
  { id: 'Creative Art', name: 'Creative Art', icon: Brush },
  { id: 'Media', name: 'Media', icon: Video },
  { id: 'Content Creation', name: 'Content Creation', icon: Sparkles },
  { id: 'Design', name: 'Design', icon: PenTool },
  { id: 'Writing', name: 'Writing', icon: Feather },
  { id: 'Illustration', name: 'Illustration', icon: Paintbrush },
];

export default {
  MAIN_INTERESTS,
  CREATIVITY_SUBCATEGORIES,
};
