const clubsData = [
  {
    name: 'ACM Club',
    initials: 'ACM',
    category: 'Technical',
    description: 'The premier student chapter advancing computing as a science and a profession through hackathons, algorithms, and technical initiatives.',
    memberCount: 280,
    followerCount: 1420,
    logoColor: 'from-blue-600 to-indigo-600',
  },
  {
    name: 'AssetMerkle Club',
    initials: 'AMC',
    category: 'Technical',
    description: 'Empowering students in Web3, blockchain infrastructure, smart contracts, and decentralized finance with real-world builds.',
    memberCount: 190,
    followerCount: 980,
    logoColor: 'from-purple-600 to-pink-600',
  },
  {
    name: 'TEDx',
    initials: 'TED',
    category: 'Literary',
    description: 'Independently organized TED-like events sparking deep discussion, innovative ideas, and inspiring campus storytelling.',
    memberCount: 110,
    followerCount: 1850,
    logoColor: 'from-red-600 to-rose-600',
  },
  {
    name: 'Economics Society',
    initials: 'ECO',
    category: 'Business & Entrepreneurship',
    description: 'Fostering critical thinking on macroeconomic policies, behavioral economics, equities, and market research.',
    memberCount: 140,
    followerCount: 760,
    logoColor: 'from-amber-600 to-orange-600',
  },
  {
    name: 'Green Sphere',
    initials: 'GSP',
    category: 'Social & Environment',
    description: 'Leading campus sustainability, e-waste audits, tree plantation drives, and green policy advocacy across universities.',
    memberCount: 210,
    followerCount: 620,
    logoColor: 'from-emerald-600 to-teal-600',
  },
  {
    name: 'Microsoft Society (MSC)',
    initials: 'MSC',
    category: 'Technical',
    description: 'Microsoft Learn Student Ambassadors campus chapter exploring cloud technologies, Azure, DevOps, and AI innovation.',
    memberCount: 250,
    followerCount: 1340,
    logoColor: 'from-cyan-600 to-blue-700',
  },
  {
    name: 'Synergy',
    initials: 'SYN',
    category: 'Sports',
    description: 'The apex campus sports council organizing intra-university leagues, athletic meets, and physical wellness marathons.',
    memberCount: 310,
    followerCount: 1150,
    logoColor: 'from-orange-600 to-red-600',
  },
  {
    name: 'Taranum Music Society',
    initials: 'TMS',
    category: 'Cultural',
    description: 'Vocalists, instrumentalists, and music producers coming together for acoustic evenings, battles of bands, and studio jams.',
    memberCount: 95,
    followerCount: 890,
    logoColor: 'from-violet-600 to-purple-800',
  },
  {
    name: 'Developer Student Club (DSC)',
    initials: 'DSC',
    category: 'Technical',
    description: 'Building mobile and web solutions for community problems supported by modern open-source toolkits and developer bootcamps.',
    memberCount: 290,
    followerCount: 1670,
    logoColor: 'from-emerald-500 to-sky-600',
  },
  {
    name: 'Art Collective',
    initials: 'ART',
    category: 'Arts & Media',
    description: 'Fine arts, digital illustration, street installations, and visual storytelling celebrating student creativity.',
    memberCount: 85,
    followerCount: 730,
    logoColor: 'from-fuchsia-600 to-rose-600',
  },
];

module.exports = { clubsData };
